spring:
  data: 
    mongodb:
      host: localhost
      port: 27017
      database: stockdb
 
  datasource:
    url: jdbc:mysql://zensarzen.com:3306/zenstockdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mala@123
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
